### ISSUE TITLE
Merging features to engelsystem/engelsystem

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#167] opened 2016-07-14 18:47 UTC
We need to keep in mind to push the latest and final change while pushing to the engelsystem. There are many features that were implemented initially and then improved. We need to create modules of each. Example as in the registration form:
- I updated some fields
- Then you updated some fields
- You changed positions
- I changed some fields
- I added reCaptcha
- You changed the background 

So there are many changes that were made to the same thing.  We need to figure out how to push those codes. We'll need to make modules. Example for the registration form:
- While making commits again, we need to make commits step by step to the branch `engelsystem-features` as we did earlier on the project. Like, First I added the new fields, then you changed background and positioning, and so on.

or what we can do is, The individual PR's that we made earlier in our repository, we can make the same to the engelsystem/engelsystem again. 
Merging features individually to engelsystem/engelsystem will take a lot of time. We would require defining a proper workflow, as there as some features that depend on other features as well. 
 @vuhung: @hongquan: Can you suggest a proper workflow for doing this?

**Comment by mariobehling** [comment] 2016-07-14 18:59
> The individual PR's that we made earlier in our repository, we can make the same to the engelsystem/engelsystem again

This is too complicated to review as there were so many small steps and they would be confusing. Making the changes into "modules" sounds best.

**Comment by hongquan** [comment] 2016-07-15 03:11
How do you do "We'll need to make modules"?

**Comment by DishantK1807** [comment] 2016-07-15 03:18
@hongquan: cc: @mariobehling: That is the problem, "making it into modules". There are overlapping features, example, changing the position/layout of fields in registration form comes in both, registration fields as well as UI/UX. If we add it to the UI/UX module, other features will be difficult to commit to the registration form. We would require making the changes again, step by step. 

Also if we use our old code, there will be errors in those codes(whitespaces, variable name, etc) that already existed in the original engelsystem code and were removed in some recent commits.

**Comment by hongquan** [comment] 2016-07-15 03:59
I don't understand what is your "module" in this context. Why

> If we add it to the UI/UX module, other features will be difficult to commit to the registration form. We would require making the changes again, step by step.

I only figure out that if many people make change in the same file, there will happens conflict when committing to git.

Example, there is line:

```
The sun rises at 6am
```

Person A change it to

```
The sun rises at 7am

```

Person B, at the same time, change to

```
The moon rises at 6pm
```

But person A commits first. Then person B commits. Conflict will occurs with person B, because Git (on B side) is told to change from "The sun rises at 6am" to "The moon rises at 6pm", but it cannot find the original line. It finds "The sun rises at 7am" instead. In this case, person B has to solve conflict manually, by communicating with person A what should be the final version, or decides her/himself.

So, there will be no case of "making the changes again". If there is, it is because you guys solved the conflict wrongly, and making lost the work which your team did.

**Comment by DishantK1807** [comment] 2016-07-15 04:19
@hongquan: That's not what I meant to say. Here is one case:
- At the beginning, I added some more fields in the registration form. (Feature 1)
- Then Sreeja made some change to UI/UX of the registration form. (Feature 2)
- Then I added some more fields to it. (Feature 3)
- Sreeja changed the background to white. (Feature 4)

Now they are all different features, if we merge them individually, it will be a lot of PR's and we would need to wait a lot of time to get each code reviewed, and the current code in the registration form contains more features too. How to merge many features into one?

**Comment by vuhung** [comment] 2016-07-15 04:30
The only and the best git flow I follow until now is this: http://nvie.com/posts/a-successful-git-branching-model/

First, branching by git issues (feature-xxx, hotfix-xxx,
then develop,
release-xxx,
and master

The issues on the way we work with @DishantK1807 mention can be improved with CI, that means, integrate (PR) as often as we can. 

Code review is another Agile practice in my Agile toolset arsenal.

In this project, we only have two developers, with some mentor so doing cross review can be hard as we don't have enough time for those activities. 

If possible, I recommend two students to review PR from each other as often as possible.

One more thing :) commit early, commit often, make the changes (PR) as small as possible, but not too small, so that reviewing can be done easier.

**Comment by hongquan** [comment] 2016-07-15 06:40
> if we merge them individually

Can you remind me you merge from where to where?

**Comment by DishantK1807** [comment] 2016-07-15 06:52
> Can you remind me you merge from where to where?

@hongquan: From this repo to the engelsystem/engelsystem

**Comment by mariobehling** [comment] 2016-07-15 07:25
There is no perfect way to merge the changes to Engelsystem. The contribution history is too diverse. We need to do it the slow way. Just merge it step by step.

@DishantK1807 As discussed yesterday please proceed. Let's see if we can get one merge of one feature for the beginning.

@hongquan Could you please close this PR: https://github.com/engelsystem/engelsystem/pull/262

**Comment by mariobehling** [comment] 2016-07-15 07:27
This issue is also a duplicate of https://github.com/fossasia/engelsystem/issues/165

Closing it.

**Closed as completed by mariobehling** 2016-07-15 07:27 UTC
Labels: duplicate
